shared:
    image: buildpack-deps
    steps:
        - short: ./mocklog --lines 10
        - medium: ./mocklog --lines 150 --group 50
        - long: ./mocklog --lines 600 --time 2 --group 150
        - immediate: ./mocklog

jobs:
    main:
        requires: 
            - ~commit
            - ~pr
    two:
        requires:
            - main

    three:
        requires:
            - main
    four: 
        requires:
            - two
            - three

    detached-one: {}
    detached-two:
        requires:
            - detached-one
    detached-three:
        requires:
            - detached-two
         
