workflow:
    - two
    - three

shared:
    image: buildpack-deps

jobs:
    main:
        steps:
            - short: ./mocklog --lines 10
            - medium: ./mocklog --lines 150 --group 50
            - long: ./mocklog --lines 600 --time 2 --group 150
            - immediate: ./mocklog

    two:
        steps:
            - short: ./mocklog --lines 10
            - medium: ./mocklog --lines 150 --group 50
            - long: ./mocklog --lines 600 --time 2 --group 150
            - immediate: ./mocklog

    three:
        steps:
            - short: ./mocklog --lines 10
            - medium: ./mocklog --lines 150 --group 50
            - long: ./mocklog --lines 600 --time 2 --group 150
            - immediate: ./mocklog
